// filepath: frontend/src/constants/dummyServices.js
// Shared dummy service data for Santa Clara
export const dummyServices = [
  {
    name: "Santa Clara Catering Co.",
    service: "Catering",
    ownerName: "Alice Johnson",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 120,
    ratingValue: 4.8,
  },
  {
    name: "Clean Sweep Santa Clara",
    service: "Cleaning",
    ownerName: "Michael Lee",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 85,
    ratingValue: 4.7,
  },
  {
    name: "Plumbing Pros SC",
    service: "Plumbing",
    ownerName: "Emily Davis",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 200,
    ratingValue: 4.9,
  },
  {
    name: "Santa Clara Electricians",
    service: "Electrical",
    ownerName: "David Wilson",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 140,
    ratingValue: 4.8,
  },
  {
    name: "Green Thumb Landscaping",
    service: "Landscaping",
    ownerName: "Sarah Thompson",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 65,
    ratingValue: 4.7,
  },
  {
    name: "Perfect Paints",
    service: "Painting",
    ownerName: "Chris Martinez",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 95,
    ratingValue: 4.8,
  },
  {
    name: "Sweet Treats Bakery",
    service: "Baked Goods",
    ownerName: "Jessica Garcia",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 180,
    ratingValue: 4.9,
  },
  {
    name: "Decor Experts",
    service: "Decorating",
    ownerName: "Daniel Rodriguez",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 60,
    ratingValue: 4.7,
  },
  {
    name: "DJ Vibes",
    service: "DJ Services",
    ownerName: "Lauren Wilson",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 110,
    ratingValue: 4.8,
  },
  {
    name: "Photo Magic",
    service: "Photography",
    ownerName: "Andrew Clark",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 130,
    ratingValue: 4.9,
  },
  {
    name: "Pest Busters",
    service: "Pest Control",
    ownerName: "Olivia Lopez",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 75,
    ratingValue: 4.7,
  },
  {
    name: "Move It Movers",
    service: "Moving Services",
    ownerName: "Matthew Harris",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 155,
    ratingValue: 4.8,
  },
  {
    name: "Pet Pals",
    service: "Pet Care",
    ownerName: "Victoria King",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 90,
    ratingValue: 4.8,
  },
  {
    name: "Tutor Time",
    service: "Tutoring",
    ownerName: "William Scott",
    address: "500 El Camino Real, Santa Clara, CA 95050",
    phone: "(408) 555-1234",
    ratingsCount: 145,
    ratingValue: 4.9,
  },
];
