export const serviceTypes = [
  "Catering",
  "Cleaning",
  "Plumbing",
  "Electrical",
  "Landscaping",
  "Painting",
  "Baked Goods",
  "Decorating",
  "DJ Services",
  "Photography",
  "Pest Control",
  "Moving Services",
  "Pet Care",
  "Tutoring",
];
